apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "askme.fullname" . }}-config
  namespace: {{ .Values.client.namespace }}
  labels:
    {{- include "askme.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}